### ISSUE TITLE
GET return corrupted binary files

### ISSUE THREAD

**Issue by newbaluku** [Serverless-Devs/fc-http#14]
when trying to return a binary file (20KB) to the caller. Caller side received corrupted binary file (35KB).
[test-fc-http.zip](https://github.com/Serverless-Devs/fc-http/files/8487011/test-fc-http.zip)

can be repro using attached modified sample project. under GET /file/:filepath endpoint.

to repro, try calling GET /file/data.jpg
the return image file becomes invalid.

no problem when returning text files.

have tried to set the binary flag as such, but none of the suggested options solve the above issue.

```
// option 1:
exports.handler = serverless(app);

// option 2:
exports.handler = serverless(app, {
  binary: false     // true / false doesn't matter, problem still exists
});

// option 3:
exports.handler = serverless(app, {
  binary: ['image/*', 'application/octet-stream']
});
```

**Comment by newbaluku** [comment]
?

**Comment by heimanba** [comment]
> ?

已经找到方案哈，预计今天，最迟明天发布新版本哈

**Comment by heimanba** [comment]
> ?

Thank you for your patient support, the V1.0.1 version has been fixed

**Comment by newbaluku** [comment]
> > ?
> 
> Thank you for your patient support, the V1.0.1 version has been fixed

ok, will try it. Thanks.

**Comment by heimanba** [comment]
> > > ?
> > 
> > 
> > Thank you for your patient support, the V1.0.1 version has been fixed
> 
> ok, will try it. Thanks.

hi,Does it work?

**Comment by newbaluku** [comment]
Hi, the problem seems to be fixed.

will do more testing on other aspect.

 Thanks @heimanba

**Comment by newbaluku** [comment]
> // option 1:
> exports.handler = serverless(app);
> 
> // option 2:
> exports.handler = serverless(app, {
>   binary: false     // true / false doesn't matter, problem still exists
> });
> 
> // option 3:
> exports.handler = serverless(app, {
>   binary: ['image/*', 'application/octet-stream']
> });

tested working with the following options:

// option 1:
exports.handler = serverless(app);

// option 2:
exports.handler = serverless(app, {
  binary: ['application/octet-stream']
});
