### ISSUE TITLE
req.headers['x-forwarded-for'] is missing

### ISSUE THREAD

**Issue by newbaluku** [Serverless-Devs/fc-http#16]
I would usually get the remote IP from value of req.headers['x-forwarded-for'] when my code is running in FC custom runtime.

but when using the Nodejs runtime via the fc-http wrapper, this value is undefined.

it would be good if it can be consistent with the usage of other runtimes like FC custom (I can also get it when running in AWS lambda through the serverless-http wrapper).

if not, what is your advice on how to get it (preferably an official method that will be persistent in future implementations).

**Comment by newbaluku** [comment]
@heimanba 

did some dig around in the requestContext and found an IP in the requestContext but not sure if this is the official supported variable for Function compute handler.

```
exports.handler = serverless(app, {
  request(request, event, context) {
    request.context = event.requestContext;

   // is this caller IP?
   console.log('caller IP:', event.requestContext.identity.sourceIp)
  },
})
```

kindly please advice?

or any other officially supported way?

**Comment by newbaluku** [comment]
@heimanba any suggestion?

**Comment by heimanba** [comment]
event.fcRequest 可以获取默认的  fc的req对象，您可以从  event.fcRequest 对象中获取，当然也可以通过 event.clientIP获取 IP
![image](https://user-images.githubusercontent.com/5129967/168205388-4c0cb621-3460-47d4-a60c-cc18877fb5d2.png)
