### ISSUE TITLE
corrupted file when uploading binary file through multipart formdata 

### ISSUE THREAD

**Issue by newbaluku** [Serverless-Devs/fc-http#2]
Hi, was trying to upload binary file through multipart formdata to an Express endpoint that is wrapped by the fc-http.

for example, when a png file (27110 bytes) was uploaded, the service end received a file that has a size of 47553 bytes.

I have modify the Express example slightly to repro the issue, see attached zip.
[test-fc-http.zip](https://github.com/Serverless-Devs/fc-http/files/7460020/test-fc-http.zip)

**Comment by newbaluku** [comment]
note that uploading text file is fine.

**Comment by heimanba** [comment]
Hello, because the Serverless container is released randomly, it is not recommended to save the file on the server. It is recommended to upload the file to Aliyun OSS

**Comment by newbaluku** [comment]
Hi, the goal of the sample code is not to show saving file onto server, but rather to show that the binary file received on the server through the fc-http wrapper is corrupted when it was sent through the multipart form data method.

As such, there might be some bug in the fc-http wrapper that is causing this.

Yes. In real working server, the file would be stored on DB or OSS. I understand your point.

The issue I'm trying to demonstrate is that somehow data is corrupted when received on the server when using the fc-http wrapper in the above secenario. I have been using other wrapper and their working as expected but not this wrapper.

**Comment by newbaluku** [comment]
Hi, any help with the above?

**Comment by heimanba** [comment]
hi,we are trying to fix this bug



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 4, 2021 12:23 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Serverless-Devs/fc-http] corrupted file when uploading binaryfile through multipart formdata  (Issue #2)




 
Hi, any help with the above?

**Comment by heimanba** [comment]
Because we rely on https://github.com/dougmoscrop/serverless-http, we preliminary positioning is problems caused by the package. Have the conclusion to synchronize you at any time

**Comment by newbaluku** [comment]
Sorry, don't quite understand what u mean.

I can read Chinese, if u prefer. Thanks.

**Comment by heimanba** [comment]
我们底层依赖这个包https://github.com/dougmoscrop/serverless-http，初步判断是 这个Npm包引起的问题哈，但是需要花点时间来解决。有进展随时和您同步

**Comment by newbaluku** [comment]
ok, Thanks for the update.

**Comment by heimanba** [comment]
不好意思，这个问题不太好解决。如果您着急的话，建议使用 custom-runtime 解决

https://github.com/awesome-fc/fc-custom-demo/blob/master/nodejs12/event-demo/code/bootstrap

只需要定义bootstrap启动文件
```
#!/bin/bash
node server.js
```

**Comment by newbaluku** [comment]
ok, no worries. I've already fallback to use custom-runtime for now.

but hope to be able to use this wrapper some time later soon. for the many advantages it has over the custom-runtime:
- I don't have to bundle-in Nodejs12 and more straight forward deployment process.
- I can make use of the Initializer routine with nodejs12-runtime.
- more readable logstore output as the "Advanced Query" is a pain to look at.

just to name a few.

Thanks for your effort.

**Comment by heimanba** [comment]
收到，我们现在被几个大的特性deplay了，这个问题我会持续跟踪，有结论马上给您回复。感谢您的谅解和支持

**Comment by newbaluku** [comment]
Hi, wondering if there is any update on the above issue? Thanks.

**Comment by listenlin** [comment]
核心原因是因为getBody方法中，获取body的方式写死了为字符串类型。
解决方式：去掉body库，改为raw-body获取Buffer数据类型，再传递出去就能解决问题。

**Comment by newbaluku** [comment]
> 核心原因是因为getBody方法中，获取body的方式写死了为字符串类型。 解决方式：去掉body库，改为raw-body获取Buffer数据类型，再传递出去就能解决问题。

Thanks for identifying the bug.

@heimanba any plan to phase-in this fix into Serverless-Devs/fc-http package?

**Comment by heimanba** [comment]
我测试下哈，没有问题应该明天发布



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 17, 2022 16:50 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [Serverless-Devs/fc-http] corrupted file when uploading binaryfile through multipart formdata  (Issue #2)




  
核心原因是因为getBody方法中，获取body的方式写死了为字符串类型。 解决方式：去掉body库，改为raw-body获取Buffer数据类型，再传递出去就能解决问题。
  
Thanks for identifying the bug.
 
@heimanba any plan to phase-in this fix into Serverless-Devs/fc-http package?

**Comment by heiemooa** [comment]
缺陷已经解决，解决方式请查看 #4
